spring:
  application:
    name: shopsync
  datasource:
    url: jdbc:mysql://10.99.206.2:3306/shopsync_e_strix_com
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver
    testWhileIdle: true
    testOnBorrow: true
    validationQuery: SELECT 1
#    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8088

forceApiMock: false

node: 1