spring:
  application:
    name: shopsync
  datasource:
    url: jdbc:mysql://10.99.106.2:3306/shopsync_e_strix_com
    username: user
    password: user
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2

server:
  port: 8088

forceApiMock: false

node: 1