spring:
  application:
    name: shopsync
  datasource:
    url: @env.datasource.url@
    username: @env.datasource.username@
    password: @env.datasource.password@
    driverClassName: @env.datasource.driver@
  jpa:
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2

server:
  port: 8088

forceApiMock: @pl.estrix.forceApiMock@