spring:
  application:
    name: package-webapp
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
#    platform: h2
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2

server:
  port: 8088

forceApiMock: false